server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    client_max_body_size 7M;

    location /images/ {
        root /usr/share/nginx/html;
        autoindex on;
    }

    location /static/ {
        root /usr/share/nginx/html;
    }

    location / {
        proxy_pass http://app:8000;
    }
}